# `NumPy` (short for "Numerical Python"):

## Why `NumPy` is needed?
* Python does not have a native data type for "arrays". The closest that we have is a `list`/`tuple`
* The standard Python functions are very slow for computational purposes
* NumPy has almost every function/method for a computation built-in. 
* For a massive computation, `NumPy` functions and methods are preffered as they are very optimized and written in faster & performant languages like `C/C++`.


## How to use `NumPy` library?
1. Install the library in your virtual-enviornment.
2. Type:

In [2]:
import numpy as np

### Creating arrays in `NumPy`:
* Arrays in `NumPy` can be created via a `list` or a `tuple` collection of `Python`.

`SYNTAX`: 

array_name = np.array(tuple_or_list)

In [3]:
sample_tuple = (1, 2, 3, 4, 5)
array = np.array(sample_tuple)
print("1D array by tuple : ", array)

sample_list = [1, 2, 3, 4, 5]
array = np.array(sample_list)
print("1D array by list : ", array)


matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("2D array: ", matrix)


1D array by tuple :  [1 2 3 4 5]
1D array by list :  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


## Operation time comparision: `List` vs `NumPy` `array`


In [4]:
import time
start = time.time()
py_list = [i * 2 for i in range(1000000)]
end_time = time.time()
print("\nPython list operation time : ", end_time - start)

start = time.time()
np_array = np.arange(1000000) * 2
end_time = time.time()
print("\nNumPy operation time : ",end_time - start)




Python list operation time :  0.0548856258392334

NumPy operation time :  0.0029900074005126953


### Creating a pre-filled array
The pre-filled array/matrices can be created by:
1. `zeros` : Create a m x n array of zeros, provide the shape in a tuple (m, n)
2. `ones` : Ones: Create a m x n array of ones, provide the shape in a tuple (m, n)
3. `full` : Full matrix: Create a m x n array of a number, provide the shape in a tuple (m, n) and a fill_value (any datatype)
4. `random` : Create a m x n array of random integers, provide the shape in a tuple (m, n)
5. `arange` : Create an 1D array, equivalent to a for loop's range function.

In [5]:
# Zeros: provide the shape in a tuple (m, n)
zeros = np.zeros(shape = (3, 4))
print("zeros array: \n", zeros)

# Ones: Create a m x n array of ones, provide the shape in a tuple (m, n)
ones = np.ones(shape = (2, 3))
print("one array: \n", ones)

# Full matrix: Create a m x n array of a number, provide the shape in a tuple (m, n) and a fill_value (any datatype)
full = np.full(shape = (2, 2), fill_value = 7)
print("full array: \n", full)
#[[7, 7]
# [7, 7]]

#random: Create a m x n array of random integers, provide the shape in a tuple (m, n)
random = np.random.random((2, 3))
print("random array: \n", random)

# arange: Create an 1D array, equivalent to a for loop's range function.
sequence = np.arange(start = 0, stop = 11,step = 2)
print("sequnce array: \n", sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.47368027 0.54859112 0.42433194]
 [0.13034473 0.71078992 0.31788618]]
sequnce array: 
 [ 0  2  4  6  8 10]


### Creating a `Vector`, `Matrix` and a `Tensor`
* ####  These are based on a rank: A rank is the number of co-ordinates required to find a particular element.

In [6]:
#1st rank tensor: A vector
vector = np.array([1, 2, 3])
print("Vector: \n", vector)

#2nd rank tensor: 
matrix = np.array([
                    [1, 2, 3], 
                    [4, 5, 6]
                  ])
print("Matrix: \n", matrix)

# 3rd rank or a higher rank tensor
tensor = np.array([
                    [
                      [1, 2], 
                      [3, 4]
                    ], 
                    [
                      [5, 6], 
                      [7, 8]
                    ]
                  ])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### `NumPy` Array Properties:

In [7]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape of array :", arr.shape)# (2, 3)
print("Dimension of array :", arr.ndim)# 2D
print("Size of array :", arr.size) # 2 x 3 = 6 elements
print("Datatype of array :", arr.dtype) # int 64

Shape of array : (2, 3)
Dimension of array : 2
Size of array : 6
Datatype of array : int64


### `Python` vs `NumPy` Operations:

In [8]:
py_list = [1, 2, 3]
np_array = np.array([1, 2, 3]) 

print("Python list multiplication ", py_list * 2)
# vs
print("Python array multiplication ", np_array * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


### Array Reshaping:

In [9]:
arr = np.arange(start = 0, stop = 12)
print("Original array \n", arr)

#Transform the array into 3 rows and 4 columns
reshaped_array = arr.reshape((3, 4))
print("Reshaped array:\n", reshaped_array)

Original array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Flattening the array:

In [10]:
#Flattened the array back into 1D
flattened = reshaped_array.flatten()
print("Flattened array:\n", flattened)

Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Ravel:

In [11]:
# ravel returns a reference to the OG array whenever possible , instead of copy
# modifying ravel could also modify the OG
raveled_array = reshaped_array.ravel()

#To confirm they are in referencing 
print(np.shares_memory(reshaped_array, raveled_array))

print("Raveled array:\n", raveled_array)

True
Raveled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Transpose:

In [12]:

# Transpose: 3 rows x 4 columns => 4 columns x 3 rows
transposed_matrix = reshaped_array.T
print("Transposed array:\n", transposed_matrix)



Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
